### ISSUE TITLE
How to view AcinoSet

### ISSUE THREAD

**Issue by DenisKochetov** [African-Robotics-Unit/acinoset_viewer#2]
Hi, I would like to use acinoset_viewer for Acinoset, but I can't figure out which files I should use. Could you please provide me with the names of the necessary files from your [Dropbox ](https://www.dropbox.com/sh/kp5kmatbv5cdjx2/AABfJGb7ktVK_L0lybOLQIbJa?dl=0)so that I can download them?

**Comment by MMathisLab** [comment]
In the read me it highlights which file to use. So in dropbox you navigate to a folder of a cheetah and pick a particular "run" and find the correct files:


![Screen Shot 2023-07-14 at 5 00 31 PM](https://github.com/African-Robotics-Unit/acinoset_viewer/assets/28102185/f28c5814-31d5-45d7-8070-4a661137a48a)
